import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type AppLanguage = 'bn' | 'hi' | 'en';

export interface LanguageOption {
  code: AppLanguage;
  label: string;
  nativeLabel: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'en', label: 'English', nativeLabel: 'English' },
];

export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  bn: {
    // Brand & Common
    app_name: 'গপ্পো কাহিনী',
    brand_part1: 'গপ্পো',
    brand_part2: 'কাহিনী',
    app_subtitle: 'রোমাঞ্চ • শান্তি • মানুষের জীবন কথা',
    footer_tagline: 'বাংলার নিখাদ রোমাঞ্চ ও মানুষের জীবনের সত্য কথা',
    footer_rights: 'সর্বস্বত্ব সংরক্ষিত',
    footer_platform: 'গপ্পো কাহিনী অডিও প্ল্যাটফর্ম',
    listen: 'শুনুন',
    pause: 'পজ করুন',
    see_all: 'সবগুলো দেখুন',
    show_less: 'কম দেখুন',
    close: 'বন্ধ করুন',
    search_placeholder: 'গল্প, কথক বা লেখক খুঁজুন...',
    search_aria: 'অনুসন্ধান',
    login: 'লগইন',
    logout: 'লগআউট',
    my_account: 'আমার অ্যাকাউন্ট',
    theme_light: 'লাইট মোড চালু করুন',
    theme_dark: 'ডার্ক মোড চালু করুন',
    menu: 'মেনু',
    menu_title: 'গপ্পো কাহিনী মেনু',
    language: 'ভাষা',
    select_language: 'ভাষা নির্বাচন',
    select_language_sub: 'অ্যাপ ইন্টারফেসের ভাষা পরিবর্তন করুন',
    theme_change: 'থিম ও রঙ পরিবর্তন',
    theme_change_sub: 'লাইট নাকি ডার্ক — আপনার পছন্দ মতো বেছে নিন',
    light_theme: 'পার্পল ও হোয়াইট (লাইট)',
    dark_theme: 'ডার্ক পার্পল ও ব্ল্যাক (ডার্ক)',
    theme_purple_white: 'পার্পল ও হোয়াইট',
    theme_perfect_light: 'পারফেক্ট লাইট মোড',
    theme_purple_black: 'পার্পল ও ব্ল্যাক',
    theme_dark_night: 'ডার্ক নাইট মোড',
    back: 'ফিরে যান',
    submit: 'জমা দিন',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    share: 'শেয়ার করুন',
    copied: 'কপি করা হয়েছে',
    loading: 'লোড হচ্ছে...',

    // Hero Section
    hero_tagline: 'প্রতিটি গল্পে এক নতুন অনুভূতি',
    hero_subtitle: 'হৃদয় ছোঁয়া বাংলা গল্প ও প্রশান্তিময় সুর',
    today_featured: 'আজকের বিশেষ গল্প',
    pass_active: 'পাস সক্রিয় (ম্যানেজ করুন)',
    top_rated: 'শীর্ষ রেটেড',
    open_stories_badge: 'টি উন্মুক্ত',

    // Home Story Sections
    new_releases_title: 'নতুন প্রকাশিত গল্প',
    new_releases_sub: 'সর্বশেষ যুক্ত হওয়া রোমাঞ্চকর ও মনোগ্রাহী গল্প',
    popular_trending_title: 'জনপ্রিয় ও ট্রেন্ডিং গল্প',
    popular_trending_sub: 'শ্রোতাদের সর্বাধিক পছন্দের ও সবচেয়ে বেশি শোনা গল্প',
    free_stories_title: 'ফ্রি গল্প',
    free_stories_sub: 'কোনো পাস ছাড়াই সম্পূর্ণ বিনামূল্যে উন্মুক্ত গল্প',
    this_month_title: 'এই মাসের গল্প',
    this_month_sub: 'চলতি মাসে প্রকাশিত বিশেষ আকর্ষণীয় গল্পসমূহ',
    mega_premium_title: 'মেগা প্রিমিয়াম সিরিজ',
    mega_premium_sub: 'দীর্ঘ উপন্যাসধর্মী ধারাবাহিক ও এক্সক্লুসিভ মেগা অডিও',

    // Card Badges & Story Meta
    badge_new: 'নতুন',
    badge_free: 'ফ্রি গল্প',
    badge_pass: 'পাস গল্প',
    badge_mega: 'মেগা পাস',
    purchased: 'কেনা হয়েছে',
    dur_mini_badge: 'মিনি',
    dur_med_badge: 'মাঝারি',
    dur_mega_badge: 'মেগা',
    episodes: 'পর্ব',
    rating_reviews: 'রেটিং ও মন্তব্য',
    bookmark: 'বুকমার্ক করুন',

    // Filter & Explore
    filter_explore: 'ফিল্টার ও এক্সপ্লোর',
    filter_explore_title: 'ফিল্টার ও এক্সপ্লোর',
    filter: 'ফিল্টার',
    filter_btn: 'ফিল্টার',
    filter_results: 'খোঁজার ফলাফল',
    search_results_title: 'খোঁজার ফলাফল',
    stories_count: 'টি গল্প',
    stories_found: 'টি গল্প',
    reset_all: 'সব রিসেট করুন',
    reset_all_filters_btn: 'সব ফিল্টার রিসেট করুন',
    clear_all: 'সব মুছুন',
    view_results: 'ফলাফল দেখুন',
    active_filters: 'সক্রিয় ফিল্টার:',
    no_stories_found: 'আপনার পছন্দের কোনো গল্প পাওয়া যায়নি। ফিল্টার পরিবর্তন করে দেখুন।',
    see_all_sectors: 'সব গল্প দেখুন',
    see_all_sectors_btn: 'সব গল্প দেখুন',
    view_layout_sectors: 'সেক্টর',
    view_layout_grid: 'গ্রিড',

    // Quick Tabs
    tab_all_stories: 'সব গল্প',
    tab_free: 'ফ্রি গল্প',
    tab_popular: 'জনপ্রিয়',
    tab_horror: 'ভৌতিক',
    tab_thriller: 'রোমাঞ্চ',
    tab_mystery: 'রহস্য',
    tab_sleep: 'ঘুমের গল্প',

    // Filter Drawer Groups
    genre_heading: 'জনরা / বিষয়',
    access_heading: 'গল্পের ধরন',
    duration_heading: 'গল্পের দৈর্ঘ্য',
    sort_heading: 'সাজানোর ক্রম',

    // Genre Translations
    genre_all: 'সব ধারা',
    genre_horror: 'ভৌতিক ও অলৌকিক',
    genre_mystery: 'রহস্য ও গোয়েন্দা',
    genre_thriller: 'রোমাঞ্চ ও থ্রিলার',
    genre_sleep: 'ঘুমের গল্প ও প্রশান্তি',
    genre_folklore: 'ঐতিহাসিক ও লোকগাথা',
    genre_romance: 'বাস্তব ও রূপকথা',
    genre_romantic: 'প্রেম ও রোমান্স (রোমান্টিক গল্প)',

    // Access options
    access_all: 'সব গল্প',
    access_free: 'ফ্রি গল্প (উন্মুক্ত)',
    access_pass: 'পাস গল্প (প্রিমিয়াম)',

    // Duration options
    dur_all: 'সব দৈর্ঘ্য',
    dur_all_sub: 'সকল গল্প',
    dur_mini: 'ছোট গল্প',
    dur_mini_sub: '< ১০ মিনিট',
    dur_medium: 'মাঝারি গল্প',
    dur_medium_sub: '১০ - ২৫ মিনিট',
    dur_mega: 'মেগা গল্প',
    dur_mega_sub: '২৫+ মিনিট',

    // Sort options
    sort_trending: 'প্রস্তাবিত ও ট্রেন্ডিং',
    sort_popular: 'সর্বাধিক শোনা',
    sort_rating: 'শীর্ষ রেটিং',

    // Mobile Bottom Nav
    nav_stories: 'গল্পঘর',
    nav_life_stories: 'জীবন কথা',
    nav_ambience: 'আবহ',
    nav_bookmarks: 'বুকমার্ক',
    nav_pass: 'পাস',
    nav_my_pass: 'আমার পাস',

    // Side Menu Drawer
    content_sections: 'কন্টেন্ট বিভাগ',
    library_features: 'লাইব্রেরি ও অডিও ফিচার',
    library_features_sub_user: 'ইতিহাস, বুকমার্ক ও সাউন্ড মিক্সার',
    login_required_features: 'লগইন আবশ্যক (User Only)',
    listening_history: 'শোনার ইতিহাস',
    saved_bookmarks: 'সংরক্ষিত গল্প (বুকমার্ক)',
    ambient_mixer_title: 'আবহ ধ্বনি মিক্সার (বৃষ্টি, নদী, বন)',
    offline_sleep_timer: 'অফলাইন অডিও ও স্লিপ টাইমার',
    coming_soon: 'শীঘ্রই আসছে',
    community_info: 'কমিউনিটি ও তথ্য',
    community_info_sub: 'কথক অডিশন, পরিচিতি ও নীতি',
    join_narrator: 'কথক হিসেবে যোগ দিন (ভয়েস)',
    about_us: 'আমাদের কথা ও উদ্দেশ্য',
    about_tab_mission: 'আমাদের উদ্দেশ্য ও টিম',
    about_tab_contact: 'সরাসরি যোগাযোগ ও মতামত',
    our_vision: 'আমাদের লক্ষ্য ও দৃষ্টিভঙ্গি',
    our_team: 'আমাদের দল ও প্রতিষ্ঠাতা পরিষদ',
    about_sub_tagline: 'বাংলার ঐতিহ্যবাহী অডিও কাহিনী, রোমাঞ্চ ও মানুষের সত্য জীবন কথা।',
    edit_in_admin: 'অ্যাডমিন প্যানেলে এডিট করুন',
    youtube_message_title: 'আমাদের ইউটিউব শ্রোতাদের জন্য বিশেষ বার্তা',
    members_connected: 'জন সদস্য যুক্ত আছেন',
    founder: 'প্রতিষ্ঠাতা',
    joined_label: 'যুক্ত হয়েছেন:',
    have_feedback_prompt: 'কোনো পরামর্শ বা বক্তব্য আছে? সরাসরি লিখুন',
    contact_admin_title: 'সরাসরি যোগাযোগ করুন',
    contact_admin_sub: 'আপনার যেকোনো অনুভূতি, পরামর্শ বা কাহিনীর অনুরোধ সরাসরি লিখুন। এটি সরাসরি অ্যাডমিন প্যানেলে জমা হবে।',
    msg_sent_success: 'আপনার বার্তা সফলভাবে পৌঁছেছে!',
    msg_sent_desc: 'ধন্যবাদ! আপনার বার্তা সরাসরি অ্যাডমিন ইনবক্সে যুক্ত হয়েছে।',
    send_another_msg: 'আরেকটি বার্তা পাঠান',
    your_name: 'আপনার নাম *',
    your_name_placeholder: 'আপনার সম্পূর্ণ নাম',
    your_email: 'ইমেইল ঠিকানা *',
    your_message: 'বার্তা বা মন্তব্য *',
    message_placeholder: 'আপনার মনের কথা বিস্তারিতভাবে লিখুন...',
    sending: 'পাঠানো হচ্ছে...',
    send_message_btn: 'বার্তা পাঠান',
    legal_and_support: 'আইন ও সহায়তা',
    legal_subtitle: 'ভারতীয় ডিজিটাল ও সাংবিধানিক আইন অনুপালন',
    account_prompt_title: 'শ্রোতা একাউন্ট খুলুন বা লগইন করুন',
    account_prompt_sub: 'লাইব্রেরি ফিচার ব্যবহার ও পাস সক্রিয় করতে',
    login_or_register: 'লগইন / নতুন অ্যাকাউন্ট',
    pass_card_title_active: 'গপ্পো কাহিনী পাস (সক্রিয়)',
    pass_card_title_inactive: 'গপ্পো কাহিনী মাসিক পাস',
    pass_card_sub_active: 'সকল গল্প আনলিমিটেড উপভোগ করুন',
    pass_card_sub_inactive: 'মাত্র ₹২০/মাস — সব গল্প আনলক',
    pass_status_info: 'পাস স্ট্যাটাস ও তথ্য',
    take_pass_btn: 'মাসিক পাস নিন',
    profile_and_pass: 'প্রোফাইল ও পাস',
    badge_pass_active: 'পাস সক্রিয়',
    locked: 'লক',
    active_count: 'সক্রিয়',
    narrator_audition: 'কথক অডিশন',
    creator_studio: 'স্টুডিও',
    login_required_bookmarks: 'বুকমার্ক ও সংরক্ষিত গল্প দেখতে অনুগ্রহ করে প্রথমে লগইন করুন।',
    login_required_history: 'পূর্বে শোনা গল্পের তালিকা দেখতে অনুগ্রহ করে প্রথমে লগইন করুন।',

    // Life Stories Section
    life_stories_title: 'মানুষের জীবন কথা',
    life_stories_sub: 'বাস্তব জীবনের অমূল্য অভিজ্ঞতা ও সাধারণের অসাধারণ গল্প',
    life_stories_badge: 'আমাদের কথা • বিশেষ পডকাস্ট সিরিজ',
    life_stories_hero_desc: 'প্রত্যেক সাধারণ মানুষের ভেতরেই লুকিয়ে থাকে এক অসাধারণ লড়াই ও জীবনের গল্প। বাংলার বিভিন্ন প্রান্তের সাধারণ মানুষের সত্য জীবনের না-বলা প্রামাণ্য অডিও পডকাস্ট।',
    life_stories_active_pass: 'আপনার অল-অ্যাক্সেস পাস সক্রিয় (সব পর্ব আনলকড)',
    life_stories_pass_req: 'জীবন কথা পডকাস্ট শুনতে পাস প্রয়োজন • আনলক করুন',
    featured_badge: 'জনপ্রিয়',
    btn_listen_podcast: 'পডকাস্ট শুনুন',
    life_story_pass_required: 'জীবন কথা শুনতে ২০ টাকার পাস প্রয়োজন',
    listened_times_count: 'বার',
    community_invite_title: 'আপনার চেনা কোনো সাধারণ মানুষের কি কোনো অসাধারণ স্মৃতি আছে?',
    community_invite_desc: 'আপনার প্রতিবেশী, কোনো প্রবীণ মানুষ বা আপনার নিজের জীবনের সত্য গল্প আমাদের সাথে শেয়ার করুন। আমরা সরাসরি ফোনে বা অনলাইনে রেকর্ডিংয়ের ব্যবস্থা করব।',
    community_invite_btn: '🎙️ গল্প জানাতে এখানে ক্লিক করুন',
    tell_your_story: 'আপনার জীবনের গল্প বলুন (পডকাস্ট)',
    be_our_guest: 'আপনিও হতে পারেন আমাদের পরবর্তী পডকাস্টের অতিথি',
    listen_podcast: 'পডকাস্ট শুনুন',
    pause_podcast: 'পজ করুন',
    tag_all: 'সব',
    tag_experience: 'বাস্তব অভিজ্ঞতা',
    tag_struggle: 'সংগ্রাম ও জয়',
    tag_memory: 'অলৌকিক স্মৃতি',
    tag_folklore: 'লোকসংস্কৃতি',

    // Player Bar & Full Player Modal
    return_to_home: 'হোমে ফিরুন',
    player_tab: 'প্লেয়ার',
    script_tab: 'স্ক্রিপ্ট',
    chapters_tab: 'অধ্যায়',
    reviews_tab: 'রিভিউ',
    ambient_sound: 'আবহ শব্দ',
    sleep_timer: 'স্লিপ টাইমার',
    sleep_timer_off: 'টাইমার বন্ধ',
    minute_abbrev: 'মিনিট',
    speed: 'গতি',
    book_page: 'বইয়ের পাতা',
    author_label: 'রচনা',
    narrator_label: 'কণ্ঠে',
    sec_back: '১৫ সেকেন্ড পেছনে',
    sec_forward: '১৫ সেকেন্ড সামনে',
    dismiss_player: 'প্লেয়ার বন্ধ করুন',
    fullscreen_player: 'ফুল স্ক্রিন প্লেয়ার',
    review_modal_title: 'রিভিউ ও রেটিং',
    review_podcast_badge: 'জীবন কথা পডকাস্ট',
    review_story_badge: 'অডিও গল্প',
    review_section_sub: 'শ্রোতাদের মতামত ও বাস্তব ৫-স্টার রেটিং সেকশন',
    verified_listener_ratings: 'যাচাইকৃত শ্রোতা রেটিং',
    how_was_story: 'গল্পটি শুনে কেমন লাগল?',
    how_was_story_sub: 'রেটিং ও আপনার অনুভূতি জানাতে অনুগ্রহ করে আপনার অ্যাকাউন্টে লগইন করুন।',
    login_to_rate_btn: 'লগইন করে রেটিং দিন',
    update_review: 'আপনার রিভিউ আপডেট করুন',
    give_rating_comment: 'রেটিং ও মন্তব্য দিন',
    previous_rating: 'পূর্বের রেটিং',
    review_success: 'আপনার রেটিং ও মন্তব্য সফলভাবে সংরক্ষিত হয়েছে!',
    select_rating: 'রেটিং বাছুন',
    commenter: 'মন্তব্যকারী',
    review_placeholder: 'গল্পের অনুভূতি, আবহের মান বা সাউন্ড কোয়ালিটি নিয়ে আপনার মতামত লিখুন...',
    saving: 'সংরক্ষণ হচ্ছে...',
    publish_comment: 'মন্তব্য প্রকাশ করুন',
    all_comments: 'সকল মন্তব্য',
    reviews_loading: 'মন্তব্য লোড হচ্ছে...',
    no_reviews_yet: 'এখনো কোনো মন্তব্য নেই। প্রথম রিভিউটি আপনিই দিন!',
    your_review_badge: 'আপনার রিভিউ',
    edit_your_review: 'আপনার রিভিউ এডিট করুন',
    like_btn: 'ভালো লেগেছে',
    total_listeners_rated: 'জন শ্রোতার রেটিং',
    no_ratings_yet: 'এখনো কোনো রেটিং নেই • প্রথম রেটিংটি আপনি দিন!',
    read_script: 'স্ক্রিপ্ট পড়ুন',
    give_rating: 'রেটিং দিন',
    font_size: 'ফন্ট',
    chapter_tap_hint: 'যেকোনো অধ্যায়ে ট্যাপ করে সরাসরি সেই অংশ থেকে শুনুন:',
    episode_prefix: 'পর্ব',
    script_loading: 'স্ক্রিপ্ট প্রস্তুত হচ্ছে...',
    author_prefix: 'লেখক',
    narrator_prefix: 'কথক',
    add_note_at: 'নোট রাখুন',
    write_short_note: 'একটি ছোট নোট লিখুন...',
    save_btn: 'সেভ করুন',
    cancel_btn: 'বাতিল',

    // Bookmarks & History Modals
    bookmarks_title: 'সংরক্ষিত বুকমার্ক ও নোট',
    no_bookmarks: 'এখনও কোনো বুকমার্ক সংরক্ষিত নেই',
    bookmarks_hint: 'গল্প শোনার সময় বুকমার্ক আইকনে ট্যাপ করে বিশেষ অংশ ও নোট সেভ করে রাখতে পারেন।',
    delete_bookmark: 'বুকমার্ক মুছুন',
    history_title: 'শোনার ইতিহাস',
    history_sub: 'পূর্বে যে গল্পগুলো আপনি শুনেছেন বা চালু করেছিলেন',
    no_history: 'ইতিহাসে কোনো গল্প নেই',
    no_history_hint: 'আপনি এখনো কোনো গল্প শোনেননি। গল্পঘর থেকে যেকোনো গল্প প্লে করলে তা স্বয়ংক্রিয়ভাবে এখানে সংরক্ষিত হবে।',
    clear_history: 'ইতিহাস মুছুন',
    replay: 'পুনরায় শুনুন',
    remove_from_list: 'তালিকা থেকে সরান',
    total_stories_saved: 'মোট সংরক্ষিত গল্প:',

    // Ambient Mixer Modal
    ambient_mixer_heading: 'ব্যাকগ্রাউন্ড সাউন্ড মিক্সার',
    ambient_mixer_desc: 'গল্প শোনার সময় ব্যাকগ্রাউন্ডে নিজের পছন্দমতো পরিবেশ তৈরি করুন।',
    soundscape_badge: 'আবহ সঙ্গীত ও সাউন্ডস্কেপ',
    soundscape_rain: 'ঝুম বৃষ্টি',
    soundscape_campfire: 'অগ্নিকুণ্ডের শব্দ',
    soundscape_ocean: 'সমুদ্রের ঢেউ',
    soundscape_wind: 'রাতের বাতাস ও ঝিঁঝিঁ',
    soundscape_drone: 'শান্ত সুর',
    ambient_off: 'বন্ধ',
    preset_rain_hearth: 'বৃষ্টি ও আগুন',
    preset_rain_hearth_desc: 'ঝুম বৃষ্টি + কাঠের অগ্নিকুণ্ড',
    preset_deep_slumber: 'গভীর ঘুম',
    preset_deep_slumber_desc: 'মৃদু বৃষ্টি + লো-ফাই মিষ্টি সুর',
    preset_midnight_coast: 'নিঝুম রাত',
    preset_midnight_coast_desc: 'রাতের বাতাস + সমুদ্রের ঢেউ',
    preset_cabin_retreat: 'পাহাড়ি কুটির',
    preset_cabin_retreat_desc: 'কাঠের আগুন + বনের শব্দ',
    stop_all: 'সব বন্ধ',
    done_btn: 'ঠিক আছে',

    // User Auth & Account Modals
    auth_title: 'শ্রোতা লগইন ও একাউন্ট',
    auth_prompt_pass: 'মাসিক পাস নিতে অনুগ্রহ করে প্রথমে আপনার অ্যাকাউন্টে লগইন বা সাইন আপ করুন।',
    auth_prompt_listen: 'গল্প শুনতে অনুগ্রহ করে প্রথমে আপনার অ্যাকাউন্টে লগইন করুন বা রেজিস্টার করুন।',
    library_login_prompt: 'লাইব্রেরি ও ব্যক্তিগত ফিচার ব্যবহার করতে অনুগ্রহ করে প্রথমে লগইন করুন।',
    auth_welcome: 'গপ্পো কাহিনীতে স্বাগতম! লগইন করুন এবং মাত্র ২০ টাকার পাসে সীমাহীন গল্প শুনুন।',
    auth_google_login: 'Google দিয়ে সরাসরি লগইন',
    auth_or_email: 'অথবা ইমেইল ও পাসওয়ার্ড',
    auth_login_tab: 'লগইন করুন',
    auth_signup_tab: 'নতুন একাউন্ট খুলুন',
    auth_email_label: 'আপনার ইমেইল আইডি *',
    auth_password_label: 'পাসওয়ার্ড *',
    auth_forgot_pass: 'পাসওয়ার্ড ভুলে গেছেন?',
    auth_login_btn: 'লগইন করুন ও এগিয়ে যান',
    auth_signup_btn: 'অ্যাকাউন্ট খুলুন ও এগিয়ে যান',
    auth_name_label: 'আপনার পুরো ও আসল নাম *',
    auth_phone_label: 'সক্রিয় মোবাইল নম্বর *',
    auth_pass_banner: 'লগইন শেষেই আপনি সরাসরি ২০ টাকার মাসিক পাস নিয়ে সব গল্প শুনতে পারবেন।',
    auth_google_verified: '✓ ১০০% ভেরিফায়েড গুগল অ্যাকাউন্ট সুরক্ষা',
    auth_fraud_notice: 'নিরাপত্তা নিশ্চিত করতে ফেক জিমেইল, সাময়িক ইনবক্স বা ফেক ফোন নম্বর সম্পূর্ণ নিষিদ্ধ।',
    auth_forgot_desc: 'আপনার নিবন্ধিত আসল ইমেইল আইডি দিন। আমরা Firebase-এর মাধ্যমে পাসওয়ার্ড রিসেট করার লিংক পাঠিয়ে দেব।',
    auth_send_reset_btn: 'পাসওয়ার্ড রিসেট লিংক পাঠান',
    auth_back_to_login: '← লগইন ফর্মে ফিরে যান',
    auth_confirm_pass_label: 'পাসওয়ার্ড নিশ্চিত করুন *',
    auth_strong_pass_label: 'শক্তিশালী পাসওয়ার্ড (কমপক্ষে ৮ অক্ষর) *',
    auth_google_login_success: 'Google অ্যাকাউন্টে সফলভাবে লগইন হয়েছে!',
    auth_google_login_error: 'Google লগইনে ত্রুটি হয়েছে।',
    auth_login_success: 'স্বাগতম! সফলভাবে লগইন সম্পন্ন হয়েছে।',
    auth_login_error: 'লগইন ব্যর্থ হয়েছে।',
    auth_enter_real_name: 'অনুগ্রহ করে আসল নাম লিখুন।',
    auth_enter_real_email: 'অনুগ্রহ করে আসল ও সক্রিয় ইমেইল আইডি দিন।',
    auth_enter_real_phone: 'অনুগ্রহ করে আসল মোবাইল নম্বর দিন।',
    auth_enter_strong_password: 'শক্তিশালী পাসওয়ার্ড দিন।',
    auth_passwords_mismatch: 'পাসওয়ার্ড এবং কনফার্ম পাসওয়ার্ড মেলেনি। অনুগ্রহ করে আবার টাইপ করুন।',
    auth_verification_sent: 'আপনার জিমেইল/ইমেইলে একটি ভেরিফিকেশন লিঙ্ক পাঠানো হয়েছে!',
    auth_account_created: 'অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে!',
    auth_register_failed: 'রেজিস্ট্রেশন ব্যর্থ হয়েছে।',
    auth_email_verified_congrats: 'অভিনন্দন! আপনার ইমেইল সফলভাবে ভেরিফাইড হয়েছে।',
    auth_email_not_yet_verified: 'এখনো ইমেইলটি ভেরিফাই করা হয়নি। আপনার ইনবক্স অথবা স্প্যাম ফোল্ডারের লিঙ্কে ক্লিক করে ভেরিফাই করুন।',
    auth_check_verify_error: 'ভেরিফিকেশন চেক করতে সমস্যা হয়েছে।',
    auth_resend_verify_success: 'পুনরায় ভেরিফিকেশন লিঙ্ক পাঠানো হয়েছে! ইনবক্স অথবা স্প্যাম ফোল্ডার চেক করুন।',
    auth_resend_verify_error: 'লিঙ্ক পাঠাতে ব্যর্থ হয়েছে।',
    auth_enter_account_email: 'অনুগ্রহ করে আপনার অ্যাকাউন্টের ইমেইল আইডি দিন।',
    auth_reset_link_sent: 'পাসওয়ার্ড রিসেট করার একটি লিংক পাঠানো হয়েছে! ইনবক্স অথবা স্প্যাম ফোল্ডার চেক করুন।',
    auth_reset_link_error: 'পাসওয়ার্ড রিসেট লিংক পাঠাতে সমস্যা হয়েছে।',
    account_title: 'শ্রোতা অ্যাকাউন্ট ও প্রোফাইল',
    account_sub: 'আপনার সাবস্ক্রিপশন, পাস ও ব্যক্তিগত তথ্য',
    active_pass_status: 'সক্রিয়',
    monthly_pass_title: 'মাসিক পাস',
    pass_modal_title: 'গপ্পো কাহিনী ২০ টাকার পাস',
    pass_modal_sub: 'সরাসরি UPI পেমেন্ট • স্ক্রিনশট বা UTR টাইপ করার ঝামেলা নেই',
    close_btn: 'বন্ধ',
    payment_success_title: 'অভিনন্দন! আপনার ২০ টাকার পাস সক্রিয় হয়েছে!',
    status_active_30d: 'স্ট্যাটাস: সক্রিয় (Active) • ৩০ দিন আনলিমিটেড',
    plan_label: 'প্ল্যান:',
    paid_amount_label: 'পরিশোধিত মূল্য:',
    auto_fetched_utr: 'অটো-ফেচড UTR:',
    validity_label: 'মেয়াদ:',
    validity_next_30d: 'পরবর্তী ৩০ দিন পর্যন্ত',
    pass_unlocked_desc: 'এখন আপনি গপ্পো কাহিনীর সকল গল্প, মেগা এপিসোড এবং বিশেষ অধ্যায় কোনো বাধা ছাড়াই উপভোগ করতে পারবেন।',
    start_listening: 'গল্প শোনা শুরু করুন',
    not_logged_in_warn: 'আপনি এখনো লগইন করেননি!',
    login_benefit_note: 'লগইন করলে আপনার পাস এবং হিস্ট্রি সবসময় সংরক্ষিত থাকবে।',
    login_first_google_email: 'প্রথমে Google বা ইমেইল দিয়ে লগইন করুন',
    login_active_badge: 'লগইন সক্রিয়',
    select_sub_plan: 'সাবস্ক্রিপশন প্ল্যান নির্বাচন করুন',
    popular_pass_badge: 'জনপ্রিয় পাস',
    days_30: '৩০ দিন',
    days_365: '৩৬৫ দিন',
    monthly_pass_card: 'মাসিক পাস',
    annual_pass_card: '১২ মাসের পাস',
    annual_saver_badge: 'বার্ষিক সাশ্রয়ী',
    per_month: '/ মাস',
    per_year: '/ বছর',
    official_upi_id: 'অফিসিয়াল UPI ID',
    copy: 'কপি',
    upi_apps_hint: 'যেকোনো UPI অ্যাপ দিয়ে পেমেন্ট করুন (GPay, PhonePe, Paytm)',
    auto_detected_utr_label: 'অটো-ডিটেক্টেড ট্রানজ্যাকশন আইডি (UTR):',
    auto_connected: 'স্বয়ংক্রিয়ভাবে সংযুক্ত',
    user_no_type_hint: 'ইউজারকে টাইপ করতে হবে না',
    real_contact_info_label: 'আপনার যোগাযোগের আসল তথ্য (ভুয়া তথ্য নিষিদ্ধ):',
    real_name_placeholder: 'আপনার আসল নাম (উদা: অনির্বাণ সেন)',
    real_email_placeholder: 'আপনার আসল ইমেইল (Gmail/Yahoo)',
    real_phone_placeholder: 'আসল মোবাইল নম্বর (৭-১৫ অঙ্ক)',
    payment_done_activate_btn: 'পেমেন্ট সম্পন্ন করেছি — ২০ টাকার পাস সক্রিয় করুন',
    pass_activating: 'পাস সক্রিয় হচ্ছে...',
    no_screenshot_needed_desc: 'কোনো স্ক্রিনশট বা জটিল ফর্ম পূরণ করার প্রয়োজন নেই। পেমেন্ট সম্পন্ন করে নিচের বাটনে চাপলেই আপনার ২০ টাকার পাস সাথে সাথে সক্রিয় হয়ে যাবে।',
    account_days_remaining: 'দিন বাকি',
    account_today_last_day: 'আজই শেষ দিন',
    account_renew_pass: 'পাস রিনিউ করুন',
    account_change_password: 'পাসওয়ার্ড পরিবর্তন',
    password_min_chars: 'নতুন পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।',
    password_mismatch: 'নতুন পাসওয়ার্ড ও কনফার্ম পাসওয়ার্ড মিলছে না।',
    password_changed_success: 'পাসওয়ার্ড সফলভাবে পরিবর্তন করা হয়েছে!',
    password_change_failed: 'পাসওয়ার্ড পরিবর্তন ব্যর্থ হয়েছে।',
    reminder_test_preview: 'রিমাইন্ডার টেস্ট প্রিভিউ:',
    days_7: '৭ দিন',
    days_3: '৩ দিন',
    days_1: '১ দিন',
    expired_label: 'মেয়াদ শেষ',
    my_sub_and_pass: 'আমার সাবস্ক্রিপশন ও পাস',
    refund_submitted_alert: '✓ রিফান্ডের অনুরোধ সফলভাবে জমা হয়েছে! অ্যাডমিন ব্যাংক রেকর্ড যাচাই করে আপনার অ্যাকাউন্টে টাকা ফেরত পাঠাবেন।',
    pending_verification: 'যাচাইয়ের অপেক্ষায় (Pending Verification)',
    pending_verification_desc: 'আপনার পেমেন্ট UTR নম্বরটি অ্যাডমিনের কাছে সফলভাবে জমা আছে। অ্যাডমিন ব্যাংক স্টেটমেন্টে রিসিভ হওয়া নিশ্চিত করার সঙ্গে সঙ্গে আপনার পাস সক্রিয় (Approve) করে দেবেন।',
    paid_label: 'পরিশোধ:',
    your_utr: 'আপনার UTR:',
    current_plan_heading: 'বর্তমান প্ল্যান',
    active_badge_status: 'সক্রিয় (Active)',
    start_date_label: 'শুরুর তারিখ:',
    expiry_renewal_label: 'মেয়াদ শেষ / রিনিউয়াল:',
    refund_pending_notice: 'রিফান্ডের অনুরোধ বিবেচনাধীন',
    refund_pending_desc: 'আপনার রিফান্ডের অনুরোধটি অ্যাডমিনের কাছে জমা আছে। জয় (সুপার অ্যাডমিন) ব্যাংক অ্যাকাউন্ট থেকে রিফান্ড পাঠানোর পর স্ট্যাটাস "Refunded" হিসেবে আপডেট হবে।',
    refund_completed_notice: 'রিফান্ড সম্পন্ন হয়েছে',
    refund_completed_desc: 'আপনার পেমেন্ট ব্যাংক/UPI মাধ্যমে ফেরত পাঠানো হয়েছে।',
    sub_cancelled_notice: 'সাবস্ক্রিপশন বাতিলকৃত (Cancelled)',
    sub_cancelled_desc: 'আপনার বর্তমান সাবস্ক্রিপশন বাতিল করা হয়েছে। নতুন পাস নিতে নিচে ক্লিক করুন।',
    activate_new_pass_btn: 'নতুন পাস সক্রিয় করুন',
    want_refund_btn: 'রিফান্ড চান?',
    cancel_pass_btn: 'পাস বাতিল করুন',
    refund_form_title: 'রিফান্ডের অনুরোধ ফর্ম',
    original_payment_label: 'মূল পেমেন্ট:',
    refund_reason_label: 'রিফান্ড চাওয়ার কারণ লিখুন *',
    refund_reason_placeholder: 'উদা: ভুলবশত দুবার পেমেন্ট হয়েছে / সেবা সংক্রান্ত সমস্যা...',
    send_request_btn: 'অনুরোধ পাঠান',
    confirm_cancel_question: 'আপনি কি নিশ্চিত যে পাসটি বাতিল করবেন?',
    cancel_consequence_desc: 'পাস বাতিল করলে আর স্বয়ংক্রিয় রিনিউয়াল হবে না।',
    cancel_reason_label: 'বাতিল করার কারণ (ঐচ্ছিক):',
    cancel_reason_placeholder: 'উদা: কিছুদিনের জন্য গল্প শোনা বন্ধ রাখব',
    keep_pass_btn: 'না, রাখব',
    yes_cancel_btn: 'হ্যাঁ, বাতিল করুন',

    // Legal / Policy UI
    policy_privacy: 'গোপনীয়তা নীতি',
    policy_terms: 'শর্তাবলী ও নিয়মাবলী',
    policy_data_deletion: 'অ্যাকাউন্ট ও ডেটা অপসারণ',
    policy_grievance: 'অভিযোগ ও নোডাল অফিসার',
    policy_refund: 'রিফান্ড ও বাতিলকরণ নীতি',
    policy_subscription_terms: 'সাবস্ক্রিপশন ও পাস শর্তাবলী',
    policy_community: 'কমিউনিটি ও মন্তব্য নীতি',
    policy_copyright: 'কপিরাইট ও স্বত্বাধিকার',
    policy_disclaimer: 'দাবিত্যাগ ও বিষয়বস্তু সতর্কতা',
    policy_third_party: 'তৃতীয় পক্ষের পরিষেবা',
    policy_permissions: 'অ্যাপ পারমিশন ও ডেটা ব্যবহার',
    policy_legal_info: 'আইনি সত্ত্বা ও বিচারিক এখতিয়ার',
    policy_contact: 'যোগাযোগ ও সাপোর্ট',
    policy_badge_count: '৪টি পলিসি',

    // Language Onboarding & Filtering
    language_onboarding_title: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    language_onboarding_subtitle: 'গপ্পো কাহিনীতে স্বাগতম! আপনার পছন্দের ভাষা বেছে নিন, সেই ভাষার অডিও গল্পগুলি আপনাকে আগে দেখানো হবে।',
    language_onboarding_bengali_desc: 'বাংলার সেরা রহস্য, ভৌতিক ও রোমাঞ্চকর অডিও কাহিনি',
    language_onboarding_hindi_desc: 'हिन्दी की रोंगटे खड़े कर देने वाली रहस्यमयी और सुकूनदायक कहानियाँ',
    language_onboarding_english_desc: 'Classic Victorian thrillers, deep relaxations & global tales',
    language_onboarding_confirm: 'পছন্দ নিশ্চিত করে শুরু করুন',
    language_filter_all: 'সব ভাষার গল্প',
    language_filter_bn: 'বাংলা গল্প',
    language_filter_hi: 'हिन्दी कहानियाँ',
    language_filter_en: 'English Stories',
    language_filter_title: 'গল্পের ভাষা',

    // Notification Permission Prompt
    notification_prompt_title: 'নতুন গল্পের নোটিফিকেশন অন করুন',
    notification_prompt_subtitle: 'নতুন রোমাঞ্চকর ভৌতিক ও রহস্য গল্প, বিশেষ ছাড় এবং মেগা অডিও পর্বের রিলিজ সবার আগে জানতে নোটিফিকেশন সক্রিয় করুন।',
    notification_prompt_enable: '🔔 নোটিফিকেশন অন করুন',
    notification_prompt_later: 'পরে করব',
    notification_enabled_toast: '✅ নোটিফিকেশন সফলভাবে চালু করা হয়েছে! নতুন গল্প এলেই আপনাকে জানানো হবে।',
    notification_blocked_toast: '⚠️ ব্রাউজার বা ডিভাইসে নোটিফিকেশন ব্লক করা রয়েছে। সেটিংস থেকে অনুমতি দিন।',
  },

  hi: {
    // Brand & Common
    app_name: 'Goppo Kahini',
    brand_part1: 'Goppo',
    brand_part2: 'Kahini',
    app_subtitle: 'रोमांच • शांति • जीवन की सच्ची कहानियाँ',
    footer_tagline: 'रोमांचक कहानियाँ और जीवन की सच्ची दास्तान',
    footer_rights: 'सर्वाधिकार सुरक्षित',
    footer_platform: 'Goppo Kahini ऑडियो प्लेटफॉर्म',
    listen: 'सुनें',
    pause: 'रोकें',
    see_all: 'सभी देखें',
    show_less: 'कम देखें',
    close: 'बंद करें',
    search_placeholder: 'कहानी, कथावाचक या लेखक खोजें...',
    search_aria: 'खोजें',
    login: 'लॉग इन',
    logout: 'लॉग आउट',
    my_account: 'मेरा खाता',
    theme_light: 'लाइट मोड चालू करें',
    theme_dark: 'डार्क मोड चालू करें',
    menu: 'मेनू',
    menu_title: 'Goppo Kahini मेनू',
    language: 'भाषा',
    select_language: 'भाषा चुनें',
    select_language_sub: 'ऐप इंटरफ़ेस की भाषा बदलें',
    theme_change: 'थीम और रंग बदलें',
    theme_change_sub: 'लाइट या डार्क — अपनी पसंद चुनें',
    light_theme: 'पर्पल और व्हाइट (लाइट)',
    dark_theme: 'डार्क पर्पल और ब्लैक (डार्क)',
    theme_purple_white: 'पर्पल और व्हाइट',
    theme_perfect_light: 'परफेक्ट लाइट मोड',
    theme_purple_black: 'पर्पल और ब्लैक',
    theme_dark_night: 'डार्क नाइट मोड',
    back: 'वापस',
    submit: 'जमा करें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    share: 'साझा करें',
    copied: 'कॉपी किया गया',
    loading: 'लोड हो रहा है...',

    // Hero Section
    hero_tagline: 'हर कहानी में एक नया एहसास',
    hero_subtitle: 'दिल को छू लेने वाली कहानियाँ और सुकून भरी धुनें',
    today_featured: 'आज की खास कहानी',
    pass_active: 'Pass सक्रिय है (प्रबंधित करें)',
    top_rated: 'शीर्ष रेटेड',
    open_stories_badge: 'खुली',

    // Home Story Sections
    new_releases_title: 'नई रिलीज़ कहानियाँ',
    new_releases_sub: 'हाल ही में जोड़ी गई रोमांचक कहानियाँ',
    popular_trending_title: 'लोकप्रिय और ट्रेंडिंग कहानियाँ',
    popular_trending_sub: 'श्रोताओं द्वारा सबसे अधिक पसंद की गई कहानियाँ',
    free_stories_title: 'मुफ्त कहानियाँ',
    free_stories_sub: 'बिना किसी पास के पूरी तरह मुफ्त ऑडियो कहानियाँ',
    this_month_title: 'इस महीने की कहानियाँ',
    this_month_sub: 'वर्तमान महीने में प्रकाशित विशेष कहानियाँ',
    mega_premium_title: 'मेगा प्रीमियम सीरीज़',
    mega_premium_sub: 'लंबी उपन्यास-जैसी धारावाहिक और एक्सक्लूसिव मेगा ऑडियो',

    // Card Badges & Story Meta
    badge_new: 'नया',
    badge_free: 'मुफ्त',
    badge_pass: 'Pass',
    badge_mega: 'मेगा पास',
    purchased: 'खरीदा हुआ',
    dur_mini_badge: 'मिनी',
    dur_med_badge: 'मध्यम',
    dur_mega_badge: 'मेगा',
    episodes: 'एपिसोड',
    rating_reviews: 'रेटिंग और समीक्षाएं',
    bookmark: 'बुकमार्क करें',

    // Filter & Explore
    filter_explore: 'फ़िल्टर और एक्सप्लोर',
    filter_explore_title: 'फ़िल्टर और एक्सप्लोर',
    filter: 'फ़िल्टर',
    filter_btn: 'फ़िल्टर',
    filter_results: 'खोज परिणाम',
    search_results_title: 'खोज परिणाम',
    stories_count: 'कहानियाँ',
    stories_found: 'कहानियाँ',
    reset_all: 'सब रीसेट करें',
    reset_all_filters_btn: 'सभी फ़िल्टर रीसेट करें',
    clear_all: 'सब हटाएं',
    view_results: 'परिणाम देखें',
    active_filters: 'सक्रिय फ़िल्टर:',
    no_stories_found: 'कोई कहानी नहीं मिली। कृपया फ़िल्टर बदलें।',
    see_all_sectors: 'सभी कहानियाँ देखें',
    see_all_sectors_btn: 'सभी कहानियाँ देखें',
    view_layout_sectors: 'सेक्टर',
    view_layout_grid: 'ग्रिड',

    // Quick Tabs
    tab_all_stories: 'सभी कहानियाँ',
    tab_free: 'मुफ्त',
    tab_popular: 'लोकप्रिय',
    tab_horror: 'डरावनी',
    tab_thriller: 'रोमांचक',
    tab_mystery: 'रहस्य',
    tab_sleep: 'नींद की कहानियाँ',

    // Filter Drawer Groups
    genre_heading: 'विधा / विषय',
    access_heading: 'कहानी का प्रकार',
    duration_heading: 'कहानी की अवधि',
    sort_heading: 'क्रमबद्ध करें',

    // Genre Translations
    genre_all: 'सभी विधाएं',
    genre_horror: 'डरावनी और अलौकिक',
    genre_mystery: 'रहस्य और जासूसी',
    genre_thriller: 'रोमांचक और थ्रिलर',
    genre_sleep: 'नींद की कहानियाँ और शांति',
    genre_folklore: 'ऐतिहासिक और लोकगाथा',
    genre_romance: 'वास्तविक और परियों की कथाएं',
    genre_romantic: 'प्रेम और रोमांस',

    // Access options
    access_all: 'सभी कहानियाँ',
    access_free: 'मुफ्त कहानियाँ (ओपन)',
    access_pass: 'पास कहानियाँ (प्रीमियम)',

    // Duration options
    dur_all: 'सभी अवधि',
    dur_all_sub: 'सभी कहानियाँ',
    dur_mini: 'छोटी कहानी',
    dur_mini_sub: '< 10 मिनट',
    dur_medium: 'मध्यम कहानी',
    dur_medium_sub: '10 - 25 मिनट',
    dur_mega: 'मेगा कहानी',
    dur_mega_sub: '25+ मिनट',

    // Sort options
    sort_trending: 'सुझाया गया और ट्रेंडिंग',
    sort_popular: 'सर्वाधिक सुना गया',
    sort_rating: 'शीर्ष रेटिंग',

    // Mobile Bottom Nav
    nav_stories: 'कहानियाँ',
    nav_life_stories: 'जीवन गाथा',
    nav_ambience: 'आभास',
    nav_bookmarks: 'बुकमार्क',
    nav_pass: 'Pass',
    nav_my_pass: 'मेरा Pass',

    // Side Menu Drawer
    content_sections: 'कंटेंट अनुभाग',
    library_features: 'लाइब्रेरी और ऑडियो सुविधाएं',
    library_features_sub_user: 'इतिहास, बुकमार्क और साउंड मिक्सर',
    login_required_features: 'लॉग इन आवश्यक (केवल उपयोगकर्ता)',
    listening_history: 'सुनने का इतिहास',
    saved_bookmarks: 'सहेजी गई कहानियाँ (बुकमार्क)',
    ambient_mixer_title: 'साउंड मिक्सर (बारिश, नदी, जंगल)',
    offline_sleep_timer: 'ऑफ़लाइन ऑडियो और स्लीप टाइमर',
    coming_soon: 'जल्द आ रहा है',
    community_info: 'समुदाय और जानकारी',
    community_info_sub: 'ऑडिशन, परिचय और नीतियां',
    join_narrator: 'कथावाचक के रूप में जुड़ें',
    about_us: 'हमारे बारे में और उद्देश्य',
    about_tab_mission: 'हमारा उद्देश्य और टीम',
    about_tab_contact: 'सीधा संपर्क और सुझाव',
    our_vision: 'हमारा दृष्टिकोण',
    our_team: 'हमारी टीम और संस्थापक',
    about_sub_tagline: 'पारंपरिक ऑडियो कहानियाँ, रोमांच और इंसानी ज़िंदगी के सच्चे किस्से।',
    edit_in_admin: 'एडमिन पैनल में संपादित करें',
    youtube_message_title: 'हमारे यूट्यूब श्रोताओं के लिए विशेष संदेश',
    members_connected: 'सदस्य जुड़े हुए हैं',
    founder: 'संस्थापक',
    joined_label: 'शामिल हुए:',
    have_feedback_prompt: 'कोई सुझाव या विचार? सीधे लिखें',
    contact_admin_title: 'सीधा संपर्क करें',
    contact_admin_sub: 'अपनी राय, सुझाव या कहानी का अनुरोध सीधे लिखें। यह सीधे एडमिन पैनल में जाएगा।',
    msg_sent_success: 'आपका संदेश सफलतापूर्वक भेजा गया!',
    msg_sent_desc: 'धन्यवाद! आपका संदेश सीधे इनबॉक्स में भेज दिया गया है।',
    send_another_msg: 'एक और संदेश भेजें',
    your_name: 'आपका नाम *',
    your_name_placeholder: 'आपका पूरा नाम',
    your_email: 'ईमेल पता *',
    your_message: 'संदेश या टिप्पणी *',
    message_placeholder: 'अपनी बात विस्तार से लिखें...',
    sending: 'भेजा जा रहा है...',
    send_message_btn: 'संदेश भेजें',
    legal_and_support: 'कानूनी और सहायता',
    legal_subtitle: 'भारतीय डिजिटल और कानूनी अनुपालन',
    account_prompt_title: 'श्रोता खाता खोलें या लॉग इन करें',
    account_prompt_sub: 'लाइब्रेरी सुविधाएं और पास सक्रिय करने के लिए',
    login_or_register: 'लॉग इन / नया खाता',
    pass_card_title_active: 'Goppo Kahini Pass (सक्रिय)',
    pass_card_title_inactive: 'Goppo Kahini मासिक Pass',
    pass_card_sub_active: 'सभी कहानियों का असीमित आनंद लें',
    pass_card_sub_inactive: 'सिर्फ ₹20/माह — सभी कहानियाँ अनलॉक',
    pass_status_info: 'पास स्थिति और जानकारी',
    take_pass_btn: 'मासिक Pass लें',
    profile_and_pass: 'प्रोफ़ाइल और Pass',
    badge_pass_active: 'Pass सक्रिय',
    locked: 'लॉक',
    active_count: 'सक्रिय',
    narrator_audition: 'कथावाचक ऑडिशन',
    creator_studio: 'स्टूडियो',
    login_required_bookmarks: 'बुकमार्क और सहेजी गई कहानियों के लिए कृपया पहले लॉग इन करें।',
    login_required_history: 'सुनने के इतिहास के लिए कृपया पहले लॉग इन करें।',

    // Life Stories Section
    life_stories_title: 'मानव जीवन कथा',
    life_stories_sub: 'वास्तविक जीवन के अनुभव और आम लोगों की असाधारण कहानियाँ',
    life_stories_badge: 'हमारी बात • विशेष पॉडकास्ट श्रृंखला',
    life_stories_hero_desc: 'हर आम इंसान के भीतर छिपी होती है एक असाधारण संघर्ष और जीवन की कहानी। आम लोगों के सच्चे जीवन का अनकहा ऑडियो पॉडकास्ट।',
    life_stories_active_pass: 'आपका ऑल-एक्सेस Pass सक्रिय है (सभी एपिसोड अनलॉक)',
    life_stories_pass_req: 'जीवन गाथा पॉडकास्ट सुनने के लिए Pass आवश्यक है • अनलॉक करें',
    featured_badge: 'लोकप्रिय',
    btn_listen_podcast: 'पॉडकास्ट सुनें',
    life_story_pass_required: 'जीवन कथा सुनने के लिए ₹20 पास आवश्यक है',
    listened_times_count: 'बार',
    community_invite_title: 'क्या आपके किसी परिचित के पास कोई असाधारण संस्मरण है?',
    community_invite_desc: 'अपने पड़ोसी, किसी बुजुर्ग या अपने स्वयं के जीवन की सच्ची कहानी हमारे साथ साझा करें। हम फ़ोन या ऑनलाइन रिकॉर्डिंग की व्यवस्था करेंगे।',
    community_invite_btn: '🎙️ कहानी बताने के लिए यहाँ क्लिक करें',
    tell_your_story: 'अपनी ज़िंदगी की कहानी बताएं (पॉडकास्ट)',
    be_our_guest: 'आप भी बन सकते हैं हमारे अगले मेहमान',
    listen_podcast: 'पॉडकास्ट सुनें',
    pause_podcast: 'रोकें',
    tag_all: 'सभी',
    tag_experience: 'वास्तविक अनुभव',
    tag_struggle: 'संघर्ष और जीत',
    tag_memory: 'अलौकिक यादें',
    tag_folklore: 'लोक संस्कृति',

    // Player Bar & Full Player Modal
    return_to_home: 'होम पर वापस',
    player_tab: 'प्लेयर',
    script_tab: 'स्क्रिप्ट',
    chapters_tab: 'अध्याय',
    reviews_tab: 'समीक्षाएं',
    ambient_sound: 'पृष्ठभूमि ध्वनि',
    sleep_timer: 'स्लीप टाइमर',
    sleep_timer_off: 'टाइमर बंद',
    minute_abbrev: 'मिनट',
    speed: 'गति',
    book_page: 'किताब का पन्ना',
    author_label: 'लेखक',
    narrator_label: 'कथावाचक',
    sec_back: '15 सेकंड पीछे',
    sec_forward: '15 सेकंड आगे',
    dismiss_player: 'प्लेयर बंद करें',
    fullscreen_player: 'फुल स्क्रीन प्लेयर',
    review_modal_title: 'समीक्षा और रेटिंग',
    review_podcast_badge: 'जीवन कथा पॉडकास्ट',
    review_story_badge: 'ऑडियो कहानी',
    review_section_sub: 'श्रोताओं की राय और वास्तविक 5-स्टार रेटिंग अनुभाग',
    verified_listener_ratings: 'सत्यापित श्रोता रेटिंग',
    how_was_story: 'कहानी सुनकर कैसा लगा?',
    how_was_story_sub: 'रेटिंग और अपनी राय साझा करने के लिए कृपया अपने खाते में लॉगिन करें।',
    login_to_rate_btn: 'लॉगिन करके रेटिंग दें',
    update_review: 'अपनी समीक्षा अपडेट करें',
    give_rating_comment: 'रेटिंग और समीक्षा दें',
    previous_rating: 'पिछली रेटिंग',
    review_success: 'आपकी रेटिंग और समीक्षा सफलतापूर्वक सहेजी गई!',
    select_rating: 'रेटिंग चुनें',
    commenter: 'टिप्पणीकार',
    review_placeholder: 'कहानी के अनुभव, माहौल या ध्वनि गुणवत्ता पर अपनी राय लिखें...',
    saving: 'सहेजा जा रहा है...',
    publish_comment: 'समीक्षा प्रकाशित करें',
    all_comments: 'सभी समीक्षाएं',
    reviews_loading: 'समीक्षाएं लोड हो रही हैं...',
    no_reviews_yet: 'अभी कोई समीक्षा नहीं है। पहली समीक्षा आप दें!',
    your_review_badge: 'आपकी समीक्षा',
    edit_your_review: 'अपनी समीक्षा संपादित करें',
    like_btn: 'पसंद आया',
    total_listeners_rated: 'श्रोताओं की रेटिंग',
    no_ratings_yet: 'अभी कोई रेटिंग नहीं है • पहली रेटिंग आप दें!',
    read_script: 'स्क्रिप्ट पढ़ें',
    give_rating: 'रेटिंग दें',
    font_size: 'फ़ॉन्ट',
    chapter_tap_hint: 'सीधे उस भाग से सुनने के लिए किसी भी अध्याय पर टैप करें:',
    episode_prefix: 'एपिसोड',
    script_loading: 'स्क्रिप्ट तैयार हो रही है...',
    author_prefix: 'लेखक',
    narrator_prefix: 'कथावाचक',
    add_note_at: 'नोट जोड़ें',
    write_short_note: 'एक संक्षिप्त नोट लिखें...',
    save_btn: 'सहेजें',
    cancel_btn: 'रद्द करें',

    // Bookmarks & History Modals
    bookmarks_title: 'सहेजे गए बुकमार्क और नोट्स',
    no_bookmarks: 'अभी तक कोई बुकमार्क सहेजा नहीं गया है',
    bookmarks_hint: 'कहानी सुनते समय बुकमार्क आइकन पर टैप करके विशेष हिस्से और नोट्स सहेज सकते हैं।',
    delete_bookmark: 'बुकमार्क हटाएं',
    history_title: 'सुनने का इतिहास',
    history_sub: 'जो कहानियाँ आपने पहले सुनी या शुरू की थीं',
    no_history: 'इतिहास में कोई कहानी नहीं है',
    no_history_hint: 'आपने अभी तक कोई कहानी नहीं सुनी है। कहानियों को सुनने पर वे अपने आप यहाँ जुड़ जाएंगी।',
    clear_history: 'इतिहास हटाएं',
    replay: 'फिर से सुनें',
    remove_from_list: 'सूची से हटाएं',
    total_stories_saved: 'कुल सहेजी गई कहानियाँ:',

    // Ambient Mixer Modal
    ambient_mixer_heading: 'बैकग्राउंड साउंड मिक्सर',
    ambient_mixer_desc: 'कहानी सुनते समय पृष्ठभूमि में अपने मनपसंद माहौल का आनंद लें।',
    soundscape_badge: 'पृष्ठभूमि संगीत और ध्वनि',
    soundscape_rain: 'मूसलाधार बारिश',
    soundscape_campfire: 'अलाव की आवाज',
    soundscape_ocean: 'समुद्र की लहरें',
    soundscape_wind: 'रात की हवा और झींगुर',
    soundscape_drone: 'शांत धुन',
    ambient_off: 'बंद',
    preset_rain_hearth: 'बारिश और आग',
    preset_rain_hearth_desc: 'मूसलाधार बारिश + अलाव',
    preset_deep_slumber: 'गहरी नींद',
    preset_deep_slumber_desc: 'हल्की बारिश + लो-फाई धुन',
    preset_midnight_coast: 'सन्नाटे भरी रात',
    preset_midnight_coast_desc: 'रात की हवा + समुद्र की लहरें',
    preset_cabin_retreat: 'पहाड़ी कुटिया',
    preset_cabin_retreat_desc: 'अलाव + जंगल की आवाज़ें',
    stop_all: 'सब बंद करें',
    done_btn: 'ठीक है',

    // User Auth & Account Modals
    auth_title: 'श्रोता लॉगिन और खाता',
    auth_prompt_pass: 'मासिक पास लेने के लिए कृपया पहले अपने खाते में लॉगिन या साइन अप करें।',
    auth_prompt_listen: 'कहानी सुनने के लिए कृपया पहले अपने खाते में लॉगिन करें या रजिस्टर करें।',
    library_login_prompt: 'लाइब्रेरी और व्यक्तिगत सुविधाओं का उपयोग करने के लिए कृपया पहले लॉगिन करें।',
    auth_welcome: 'Goppo Kahini में आपका स्वागत है! लॉगिन करें और ₹20 के पास में असीमित कहानियाँ सुनें।',
    auth_google_login: 'Google से सीधे लॉगिन करें',
    auth_or_email: 'या ईमेल और पासवर्ड',
    auth_login_tab: 'लॉग इन करें',
    auth_signup_tab: 'नया खाता बनाएं',
    auth_email_label: 'आपका ईमेल पता *',
    auth_password_label: 'पासवर्ड *',
    auth_forgot_pass: 'पासवर्ड भूल गए?',
    auth_login_btn: 'लॉगिन करें और आगे बढ़ें',
    auth_signup_btn: 'खाता बनाएं और आगे बढ़ें',
    auth_name_label: 'आपका पूरा नाम *',
    auth_phone_label: 'सक्रिय मोबाइल नंबर *',
    auth_pass_banner: 'लॉगिन करते ही आप सीधे ₹20 के मासिक पास से सभी कहानियाँ सुन सकते हैं।',
    auth_google_verified: '✓ 100% सत्यापित Google खाता सुरक्षा',
    auth_fraud_notice: 'सुरक्षा सुनिश्चित करने के लिए फर्जी ईमेल या अस्थायी इनबॉक्स पूरी तरह वर्जित है।',
    auth_forgot_desc: 'अपना पंजीकृत वास्तविक ईमेल आईडी दर्ज करें। हम पासवर्ड रीसेट लिंक भेजेंगे।',
    auth_send_reset_btn: 'पासवर्ड रीसेट लिंक भेजें',
    auth_back_to_login: '← लॉगिन फ़ॉर्म पर वापस जाएँ',
    auth_confirm_pass_label: 'पासवर्ड की पुष्टि करें *',
    auth_strong_pass_label: 'मजबूत पासवर्ड (कम से कम 8 अक्षर) *',
    auth_google_login_success: 'Google खाते से सफलतापूर्वक लॉगिन हो गया!',
    auth_google_login_error: 'Google लॉगिन में त्रुटि हुई।',
    auth_login_success: 'स्वागत है! सफलतापूर्वक लॉगिन संपन्न हुआ।',
    auth_login_error: 'लॉगिन विफल रहा।',
    auth_enter_real_name: 'कृपया अपना वास्तविक नाम दर्ज करें।',
    auth_enter_real_email: 'कृपया वास्तविक और सक्रिय ईमेल पता दर्ज करें।',
    auth_enter_real_phone: 'कृपया वास्तविक मोबाइल नंबर दर्ज करें।',
    auth_enter_strong_password: 'मजबूत पासवर्ड दर्ज करें।',
    auth_passwords_mismatch: 'पासवर्ड और कन्फर्म पासवर्ड मेल नहीं खा रहे हैं। कृपया पुनः प्रयास करें।',
    auth_verification_sent: 'आपके ईमेल पर सत्यापन लिंक भेजा गया है!',
    auth_account_created: 'खाता सफलतापूर्वक बनाया गया!',
    auth_register_failed: 'पंजीकरण विफल रहा।',
    auth_email_verified_congrats: 'बधाई हो! आपका ईमेल सफलतापूर्वक सत्यापित हो गया है।',
    auth_email_not_yet_verified: 'अभी तक ईमेल सत्यापित नहीं हुआ है। कृपया अपने इनबॉक्स या स्पैम फ़ोल्डर के लिंक पर क्लिक करें।',
    auth_check_verify_error: 'सत्यापन जांच में समस्या आई।',
    auth_resend_verify_success: 'सत्यापन लिंक फिर से भेजा गया! इनबॉक्स या स्पैम फ़ोल्डर देखें।',
    auth_resend_verify_error: 'लिंक भेजना विफल रहा।',
    auth_enter_account_email: 'कृपया अपने खाते का ईमेल आईडी दर्ज करें।',
    auth_reset_link_sent: 'पासवर्ड रीसेट लिंक भेजा गया! इनबॉक्स या स्पैम फ़ोल्डर देखें।',
    auth_reset_link_error: 'पासवर्ड रीसेट लिंक भेजने में समस्या आई।',
    account_title: 'श्रोता खाता और प्रोफ़ाइल',
    account_sub: 'आपकी सदस्यता, पास और व्यक्तिगत जानकारी',
    active_pass_status: 'सक्रिय',
    monthly_pass_title: 'मासिक Pass',
    pass_modal_title: 'Goppo Kahini ₹20 Pass',
    pass_modal_sub: 'सीधा UPI भुगतान • स्क्रीनशॉट या UTR टाइप करने का कोई झंझट नहीं',
    close_btn: 'बंद करें',
    payment_success_title: 'बधाई हो! आपका ₹20 पास सक्रिय हो गया है!',
    status_active_30d: 'स्थिति: सक्रिय (Active) • 30 दिन असीमित',
    plan_label: 'प्लान:',
    paid_amount_label: 'भुगतान की गई राशि:',
    auto_fetched_utr: 'ऑटो-फेच किया गया UTR:',
    validity_label: 'वैधता:',
    validity_next_30d: 'अगले 30 दिनों तक',
    pass_unlocked_desc: 'अब आप Goppo Kahini की सभी कहानियों, मेगा एपिसोड और विशेष अध्यायों का बिना किसी रुकावट आनंद ले सकते हैं।',
    start_listening: 'कहानियाँ सुनना शुरू करें',
    not_logged_in_warn: 'आप अभी लॉगिन नहीं हैं!',
    login_benefit_note: 'लॉगिन करने से आपका पास और इतिहास हमेशा सुरक्षित रहेगा।',
    login_first_google_email: 'पहले Google या ईमेल से लॉगिन करें',
    login_active_badge: 'लॉगिन सक्रिय',
    select_sub_plan: 'सब्सक्रिप्शन प्लान चुनें',
    popular_pass_badge: 'लोकप्रिय पास',
    days_30: '30 दिन',
    days_365: '365 दिन',
    monthly_pass_card: 'मासिक पास',
    annual_pass_card: '12 महीने का पास',
    annual_saver_badge: 'वार्षिक बचत',
    per_month: '/ माह',
    per_year: '/ वर्ष',
    official_upi_id: 'आधिकारिक UPI ID',
    copy: 'कॉपी करें',
    upi_apps_hint: 'किसी भी UPI ऐप से भुगतान करें (GPay, PhonePe, Paytm)',
    auto_detected_utr_label: 'ऑटो-डिटेक्टेड ट्रांजैक्शन आईडी (UTR):',
    auto_connected: 'स्वचालित रूप से जुड़ा हुआ',
    user_no_type_hint: 'यूजर को टाइप करने की जरूरत नहीं है',
    real_contact_info_label: 'आपकी वास्तविक संपर्क जानकारी (फर्जी जानकारी प्रतिबंधित):',
    real_name_placeholder: 'आपका असली नाम (उदा: अनिर्बान सेन)',
    real_email_placeholder: 'आपका असली ईमेल (Gmail/Yahoo)',
    real_phone_placeholder: 'असली मोबाइल नंबर (7-15 अंक)',
    payment_done_activate_btn: 'भुगतान पूरा किया — ₹20 पास सक्रिय करें',
    pass_activating: 'पास सक्रिय हो रहा है...',
    no_screenshot_needed_desc: 'कोई स्क्रीनशॉट या जटिल फॉर्म भरने की आवश्यकता नहीं है। भुगतान पूरा करके नीचे दिए गए बटन पर टैप करते ही आपका ₹20 पास तुरंत सक्रिय हो जाएगा।',
    account_days_remaining: 'दिन शेष',
    account_today_last_day: 'आज ही अंतिम दिन',
    account_renew_pass: 'पास रिन्यू करें',
    account_change_password: 'पासवर्ड बदलें',
    password_min_chars: 'नया पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
    password_mismatch: 'नया पासवर्ड और कन्फर्म पासवर्ड मेल नहीं खा रहे हैं।',
    password_changed_success: 'पासवर्ड सफलतापूर्वक बदल दिया गया है!',
    password_change_failed: 'पासवर्ड बदलना विफल रहा।',
    reminder_test_preview: 'रिमाइंडर टेस्ट प्रीव्यू:',
    days_7: '7 दिन',
    days_3: '3 दिन',
    days_1: '1 दिन',
    expired_label: 'अवधि समाप्त',
    my_sub_and_pass: 'मेरी सदस्यता और पास',
    refund_submitted_alert: '✓ रिफंड का अनुरोध सफलतापूर्वक दर्ज कर लिया गया है! एडमिन बैंक रिकॉर्ड की पुष्टि करके आपके खाते में राशि वापस भेज देंगे।',
    pending_verification: 'सत्यापन प्रक्रियाधीन (Pending Verification)',
    pending_verification_desc: 'आपका भुगतान UTR नंबर एडमिन के पास सफलतापूर्वक जमा है। बैंक स्टेटमेंट में पुष्टि होते ही आपका पास सक्रिय कर दिया जाएगा।',
    paid_label: 'भुगतान:',
    your_utr: 'आपका UTR:',
    current_plan_heading: 'वर्तमान प्लान',
    active_badge_status: 'सक्रिय (Active)',
    start_date_label: 'आरंभ तिथि:',
    expiry_renewal_label: 'समाप्ति / नवीनीकरण:',
    refund_pending_notice: 'रिफंड अनुरोध प्रक्रियाधीन',
    refund_pending_desc: 'आपका रिफंड अनुरोध जमा है। बैंक खाते से रिफंड भेजे जाने पर स्थिति "Refunded" हो जाएगी।',
    refund_completed_notice: 'रिफंड पूरा हो गया',
    refund_completed_desc: 'आपका भुगतान बैंक/UPI के माध्यम से वापस कर दिया गया है।',
    sub_cancelled_notice: 'सदस्यता रद्द (Cancelled)',
    sub_cancelled_desc: 'आपकी वर्तमान सदस्यता रद्द कर दी गई है। नया पास लेने के लिए नीचे क्लिक करें।',
    activate_new_pass_btn: 'नया पास सक्रिय करें',
    want_refund_btn: 'रिफंड चाहिए?',
    cancel_pass_btn: 'पास रद्द करें',
    refund_form_title: 'रिफंड अनुरोध फॉर्म',
    original_payment_label: 'मूल भुगतान:',
    refund_reason_label: 'रिफंड का कारण लिखें *',
    refund_reason_placeholder: 'उदा: गलती से दो बार भुगतान हो गया / सेवा संबंधी समस्या...',
    send_request_btn: 'अनुरोध भेजें',
    confirm_cancel_question: 'क्या आप निश्चित रूप से पास रद्द करना चाहते हैं?',
    cancel_consequence_desc: 'पास रद्द करने पर स्वचालित नवीनीकरण बंद हो जाएगा।',
    cancel_reason_label: 'रद्द करने का कारण (वैकल्पिक):',
    cancel_reason_placeholder: 'उदा: कुछ दिनों के लिए सुनना बंद कर रहा हूँ',
    keep_pass_btn: 'नहीं, चालू रखें',
    yes_cancel_btn: 'हाँ, रद्द करें',

    // Legal / Policy UI
    policy_privacy: 'गोपनीयता नीति',
    policy_terms: 'नियम और शर्तें',
    policy_data_deletion: 'खाता और डेटा हटाना',
    policy_grievance: 'शिकायत और नोडल अधिकारी',
    policy_refund: 'रिफंड और रद्दीकरण नीति',
    policy_subscription_terms: 'सब्सक्रिप्शन और पास शर्तें',
    policy_community: 'समुदाय और टिप्पणी नीति',
    policy_copyright: 'कॉपीराइट नीति',
    policy_disclaimer: 'अस्वीकरण और सामग्री चेतावनी',
    policy_third_party: 'तृतीय पक्ष सेवाएं',
    policy_permissions: 'ऐप अनुमतियाँ और डेटा उपयोग',
    policy_legal_info: 'कानूनी जानकारी और क्षेत्राधिकार',
    policy_contact: 'संपर्क और सहायता',
    policy_badge_count: '4 नीतियां',

    // Language Onboarding & Filtering
    language_onboarding_title: 'अपनी पसंदीदा भाषा चुनें',
    language_onboarding_subtitle: 'गप्पो कहानी में आपका स्वागत है! अपनी पसंदीदा भाषा चुनें, ताकि उस भाषा की ऑडियो कहानियां आपको सबसे पहले दिखाई दें।',
    language_onboarding_bengali_desc: 'बंगाली रहस्य, हॉरर और क्लासिक ऑडियो कहानियां',
    language_onboarding_hindi_desc: 'हिन्दी की रोंगटे खड़े कर देने वाली रहस्यमयी और सुकूनदायक कहानियाँ',
    language_onboarding_english_desc: 'Classic Victorian thrillers, deep relaxations & global tales',
    language_onboarding_confirm: 'पसंद सहेजें और शुरू करें',
    language_filter_all: 'सभी कहानियाँ',
    language_filter_bn: 'বাংলা গল্প',
    language_filter_hi: 'हिन्दी कहानियाँ',
    language_filter_en: 'English Stories',
    language_filter_title: 'कहानियों की भाषा',

    // Notification Permission Prompt
    notification_prompt_title: 'नई कहानियों के नोटिफिकेशन ऑन करें',
    notification_prompt_subtitle: 'हर नई रोमांचक कहानी, विशेष छूट और नए एपिसोड की ताज़ा जानकारी सबसे पहले पाने के लिए नोटिफिकेशन चालू करें।',
    notification_prompt_enable: '🔔 नोटिफिकेशन ऑन करें',
    notification_prompt_later: 'बाद में',
    notification_enabled_toast: '✅ नोटिफिकेशन सफलतापूर्वक चालू हो गया है! नई कहानी आते ही सूचित किया जाएगा।',
    notification_blocked_toast: '⚠️ डिवाइस या ब्राउज़र में नोटिफिकेशन अनुमति बंद है। कृपया सेटिंग्स से अनुमति दें।',
  },

  en: {
    // Brand & Common
    app_name: 'Goppo Kahini',
    brand_part1: 'Goppo',
    brand_part2: 'Kahini',
    app_subtitle: 'Thriller • Peace • Real Life Stories',
    footer_tagline: 'Thrilling stories and true life journeys',
    footer_rights: 'All rights reserved',
    footer_platform: 'Goppo Kahini Audio Platform',
    listen: 'Listen',
    pause: 'Pause',
    see_all: 'See All',
    show_less: 'Show Less',
    close: 'Close',
    search_placeholder: 'Search stories, narrators, authors...',
    search_aria: 'Search',
    login: 'Login',
    logout: 'Logout',
    my_account: 'My Account',
    theme_light: 'Switch to Light Mode',
    theme_dark: 'Switch to Dark Mode',
    menu: 'Menu',
    menu_title: 'Goppo Kahini Menu',
    language: 'Language',
    select_language: 'Select Language',
    select_language_sub: 'Change app interface language',
    theme_change: 'Theme & Appearance',
    theme_change_sub: 'Choose Light or Dark mode to your preference',
    light_theme: 'Purple & White (Light)',
    dark_theme: 'Dark Purple & Black (Dark)',
    theme_purple_white: 'Purple & White',
    theme_perfect_light: 'Perfect Light Mode',
    theme_purple_black: 'Purple & Black',
    theme_dark_night: 'Dark Night Mode',
    back: 'Back',
    submit: 'Submit',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    share: 'Share',
    copied: 'Copied',
    loading: 'Loading...',

    // Hero Section
    hero_tagline: 'Every story, a new feeling',
    hero_subtitle: 'Heart-touching stories and soothing sounds',
    today_featured: "Today's Featured Story",
    pass_active: 'Pass Active (Manage)',
    top_rated: 'Top Rated',
    open_stories_badge: 'available',

    // Home Story Sections
    new_releases_title: 'New Releases',
    new_releases_sub: 'Recently added thrilling and peaceful audio stories',
    popular_trending_title: 'Popular & Trending',
    popular_trending_sub: 'Top rated and most listened audio stories',
    free_stories_title: 'Free Stories',
    free_stories_sub: 'Completely free audio stories without any pass',
    this_month_title: "This Month's Stories",
    this_month_sub: 'Special stories released during current month',
    mega_premium_title: 'Mega Premium Series',
    mega_premium_sub: 'Long-form novel-like audio series and mega specials',

    // Card Badges & Story Meta
    badge_new: 'NEW',
    badge_free: 'Free',
    badge_pass: 'Pass',
    badge_mega: 'Mega Pass',
    purchased: 'Purchased',
    dur_mini_badge: 'Mini',
    dur_med_badge: 'Medium',
    dur_mega_badge: 'Mega',
    episodes: 'episodes',
    rating_reviews: 'Rating & Reviews',
    bookmark: 'Bookmark',

    // Filter & Explore
    filter_explore: 'Filter & Explore',
    filter_explore_title: 'Filter & Explore',
    filter: 'Filter',
    filter_btn: 'Filter',
    filter_results: 'Search Results',
    search_results_title: 'Search Results',
    stories_count: 'stories',
    stories_found: 'stories',
    reset_all: 'Reset All',
    reset_all_filters_btn: 'Reset All Filters',
    clear_all: 'Clear All',
    view_results: 'View Results',
    active_filters: 'Active Filters:',
    no_stories_found: 'No stories found matching your selection. Try adjusting filters.',
    see_all_sectors: 'See All Stories',
    see_all_sectors_btn: 'See All Stories',
    view_layout_sectors: 'Sectors',
    view_layout_grid: 'Grid',

    // Quick Tabs
    tab_all_stories: 'All Stories',
    tab_free: 'Free',
    tab_popular: 'Popular',
    tab_horror: 'Horror',
    tab_thriller: 'Thriller',
    tab_mystery: 'Mystery',
    tab_sleep: 'Sleep Stories',

    // Filter Drawer Groups
    genre_heading: 'Genre / Category',
    access_heading: 'Story Access',
    duration_heading: 'Duration',
    sort_heading: 'Sort Order',

    // Genre Translations
    genre_all: 'All Genres',
    genre_horror: 'Horror & Supernatural',
    genre_mystery: 'Mystery & Detective',
    genre_thriller: 'Thriller & Suspense',
    genre_sleep: 'Sleep Stories & Calm',
    genre_folklore: 'Historical & Folklore',
    genre_romance: 'Real Life & Fairytales',
    genre_romantic: 'Love & Romance',

    // Access options
    access_all: 'All Stories',
    access_free: 'Free Stories (Open)',
    access_pass: 'Pass Stories (Premium)',

    // Duration options
    dur_all: 'All Lengths',
    dur_all_sub: 'All stories',
    dur_mini: 'Short Story',
    dur_mini_sub: '< 10 mins',
    dur_medium: 'Medium Story',
    dur_medium_sub: '10 - 25 mins',
    dur_mega: 'Mega Story',
    dur_mega_sub: '25+ mins',

    // Sort options
    sort_trending: 'Recommended & Trending',
    sort_popular: 'Most Played',
    sort_rating: 'Top Rated',

    // Mobile Bottom Nav
    nav_stories: 'Stories',
    nav_life_stories: 'Life Stories',
    nav_ambience: 'Ambience',
    nav_bookmarks: 'Bookmarks',
    nav_pass: 'Pass',
    nav_my_pass: 'My Pass',

    // Side Menu Drawer
    content_sections: 'Content Sections',
    library_features: 'Library & Audio Features',
    library_features_sub_user: 'History, Bookmarks & Sound Mixer',
    login_required_features: 'Login Required (Users Only)',
    listening_history: 'Listening History',
    saved_bookmarks: 'Saved Stories (Bookmarks)',
    ambient_mixer_title: 'Ambient Sound Mixer (Rain, River, Woods)',
    offline_sleep_timer: 'Offline Audio & Sleep Timer',
    coming_soon: 'Coming Soon',
    community_info: 'Community & Info',
    community_info_sub: 'Auditions, About & Policies',
    join_narrator: 'Join as Narrator (Voice)',
    about_us: 'About Us & Mission',
    about_tab_mission: 'Our Mission & Team',
    about_tab_contact: 'Contact & Feedback',
    our_vision: 'Our Vision & Goals',
    our_team: 'Our Team & Leadership',
    about_sub_tagline: 'Traditional audio stories, thrilling tales and real-life journeys.',
    edit_in_admin: 'Edit in Admin Panel',
    youtube_message_title: 'Special Message for Our YouTube Audience',
    members_connected: 'members connected',
    founder: 'Founder',
    joined_label: 'Joined:',
    have_feedback_prompt: 'Have suggestions or feedback? Write to us',
    contact_admin_title: 'Contact Directly',
    contact_admin_sub: 'Send us your thoughts, feedback, or story requests directly.',
    msg_sent_success: 'Your message has been sent successfully!',
    msg_sent_desc: 'Thank you! Your message was delivered directly to our team.',
    send_another_msg: 'Send Another Message',
    your_name: 'Your Name *',
    your_name_placeholder: 'Your full name',
    your_email: 'Email Address *',
    your_message: 'Message or Feedback *',
    message_placeholder: 'Write your thoughts in detail...',
    sending: 'Sending...',
    send_message_btn: 'Send Message',
    legal_and_support: 'Legal & Support',
    legal_subtitle: 'Indian Digital & Legal Compliance',
    account_prompt_title: 'Open Listener Account or Login',
    account_prompt_sub: 'To access library features and active passes',
    login_or_register: 'Login / New Account',
    pass_card_title_active: 'Goppo Kahini Pass (Active)',
    pass_card_title_inactive: 'Goppo Kahini Monthly Pass',
    pass_card_sub_active: 'Enjoy unlimited access to all stories',
    pass_card_sub_inactive: 'Only ₹20/mo — Unlock all stories',
    pass_status_info: 'Pass Status & Details',
    take_pass_btn: 'Get Monthly Pass',
    profile_and_pass: 'Profile & Pass',
    badge_pass_active: 'Pass Active',
    locked: 'Locked',
    active_count: 'active',
    narrator_audition: 'Narrator Audition',
    creator_studio: 'Studio',
    login_required_bookmarks: 'Please login first to view bookmarks and saved stories.',
    login_required_history: 'Please login first to view your listening history.',

    // Life Stories Section
    life_stories_title: 'Human Life Stories',
    life_stories_sub: 'Invaluable real-life experiences and extraordinary journeys',
    life_stories_badge: 'Real Voices • Special Podcast Series',
    life_stories_hero_desc: 'Inside every ordinary person lies an extraordinary journey. The untold true documentary audio podcast of everyday lives.',
    life_stories_active_pass: 'Your All-Access Pass is active (All episodes unlocked)',
    life_stories_pass_req: 'Pass required to listen to Life Stories • Unlock Now',
    featured_badge: 'Featured',
    btn_listen_podcast: 'Listen to Podcast',
    life_story_pass_required: '₹20 pass required to listen to life stories',
    listened_times_count: 'times',
    community_invite_title: 'Do you know an ordinary person with an extraordinary story?',
    community_invite_desc: 'Share real life stories from your neighbors, elders, or yourself. We will arrange recording over phone or online.',
    community_invite_btn: '🎙️ Click here to submit a story',
    tell_your_story: 'Share Your Life Story (Podcast)',
    be_our_guest: 'You too can be our next podcast guest',
    listen_podcast: 'Listen to Podcast',
    pause_podcast: 'Pause',
    tag_all: 'All',
    tag_experience: 'Real Experience',
    tag_struggle: 'Struggle & Triumph',
    tag_memory: 'Supernatural Memory',
    tag_folklore: 'Folk Culture',

    // Player Bar & Full Player Modal
    return_to_home: 'Return Home',
    player_tab: 'Player',
    script_tab: 'Script',
    chapters_tab: 'Chapters',
    reviews_tab: 'Reviews',
    ambient_sound: 'Ambient Sound',
    sleep_timer: 'Sleep Timer',
    sleep_timer_off: 'Timer Off',
    minute_abbrev: 'min',
    speed: 'Speed',
    book_page: 'Book Page',
    author_label: 'Author',
    narrator_label: 'Narrator',
    sec_back: '15s Back',
    sec_forward: '15s Forward',
    dismiss_player: 'Close Player',
    fullscreen_player: 'Full Screen Player',
    review_modal_title: 'Reviews & Ratings',
    review_podcast_badge: 'Life Stories Podcast',
    review_story_badge: 'Audio Story',
    review_section_sub: 'Listener feedback & verified 5-star ratings',
    verified_listener_ratings: 'Verified Listener Ratings',
    how_was_story: 'How did you like the story?',
    how_was_story_sub: 'Please log in to your account to share your rating and review.',
    login_to_rate_btn: 'Log in to Rate',
    update_review: 'Update Your Review',
    give_rating_comment: 'Leave Rating & Review',
    previous_rating: 'Previous Rating',
    review_success: 'Your rating and review were saved successfully!',
    select_rating: 'Select Rating',
    commenter: 'Reviewer',
    review_placeholder: 'Share your thoughts on the story, ambiance, and audio quality...',
    saving: 'Saving...',
    publish_comment: 'Submit Review',
    all_comments: 'All Reviews',
    reviews_loading: 'Loading reviews...',
    no_reviews_yet: 'No reviews yet. Be the first to share your thoughts!',
    your_review_badge: 'Your Review',
    edit_your_review: 'Edit Your Review',
    like_btn: 'Liked',
    total_listeners_rated: 'listener ratings',
    no_ratings_yet: 'No ratings yet • Be the first to rate!',
    read_script: 'Read Script',
    give_rating: 'Rate',
    font_size: 'Font',
    chapter_tap_hint: 'Tap any chapter to listen directly from that part:',
    episode_prefix: 'Episode',
    script_loading: 'Preparing script...',
    author_prefix: 'Author',
    narrator_prefix: 'Narrator',
    add_note_at: 'Add note at',
    write_short_note: 'Write a short note...',
    save_btn: 'Save',
    cancel_btn: 'Cancel',

    // Bookmarks & History Modals
    bookmarks_title: 'Saved Bookmarks & Notes',
    no_bookmarks: 'No bookmarks saved yet',
    bookmarks_hint: 'While listening to a story, tap the bookmark icon to save specific timestamps and notes.',
    delete_bookmark: 'Delete Bookmark',
    history_title: 'Listening History',
    history_sub: 'Stories you have previously listened to or started',
    no_history: 'No listening history yet',
    no_history_hint: "You haven't listened to any stories yet. Stories you play will automatically appear here.",
    clear_history: 'Clear History',
    replay: 'Listen Again',
    remove_from_list: 'Remove from list',
    total_stories_saved: 'Total saved stories:',

    // Ambient Mixer Modal
    ambient_mixer_heading: 'Background Sound Mixer',
    ambient_mixer_desc: 'Create your perfect listening atmosphere with background sounds.',
    soundscape_badge: 'Soundscapes & Ambience',
    soundscape_rain: 'Heavy Rain',
    soundscape_campfire: 'Campfire',
    soundscape_ocean: 'Ocean Waves',
    soundscape_wind: 'Night Wind & Crickets',
    soundscape_drone: 'Calming Drone',
    ambient_off: 'Off',
    preset_rain_hearth: 'Rain & Fire',
    preset_rain_hearth_desc: 'Heavy Rain + Campfire',
    preset_deep_slumber: 'Deep Sleep',
    preset_deep_slumber_desc: 'Gentle Rain + Lo-Fi Melody',
    preset_midnight_coast: 'Midnight Coast',
    preset_midnight_coast_desc: 'Night Wind + Ocean Waves',
    preset_cabin_retreat: 'Cabin Retreat',
    preset_cabin_retreat_desc: 'Campfire + Forest Sounds',
    stop_all: 'Stop All',
    done_btn: 'Done',

    // User Auth & Account Modals
    auth_title: 'Listener Login & Account',
    auth_prompt_pass: 'Please log in or sign up first to get your monthly pass.',
    auth_prompt_listen: 'Please log in or register first to listen to stories.',
    library_login_prompt: 'Please log in first to use the library and personalized features.',
    auth_welcome: 'Welcome to Goppo Kahini! Login to enjoy unlimited stories with a pass.',
    auth_google_login: 'Continue with Google',
    auth_or_email: 'Or Email & Password',
    auth_login_tab: 'Login',
    auth_signup_tab: 'Create Account',
    auth_email_label: 'Your Email Address *',
    auth_password_label: 'Password *',
    auth_forgot_pass: 'Forgot Password?',
    auth_login_btn: 'Login & Continue',
    auth_signup_btn: 'Create Account & Continue',
    auth_name_label: 'Your Full Name *',
    auth_phone_label: 'Active Mobile Number *',
    auth_pass_banner: 'After login, you can directly get a monthly pass and listen to all stories.',
    auth_google_verified: '✓ 100% Verified Google Account Security',
    auth_fraud_notice: 'For security, fake emails, temporary inboxes or fake phone numbers are strictly prohibited.',
    auth_forgot_desc: 'Enter your registered email address. We will send a password reset link.',
    auth_send_reset_btn: 'Send Password Reset Link',
    auth_back_to_login: '← Back to Login Form',
    auth_confirm_pass_label: 'Confirm Password *',
    auth_strong_pass_label: 'Strong Password (min 8 chars) *',
    auth_google_login_success: 'Successfully logged in with Google account!',
    auth_google_login_error: 'Error logging in with Google.',
    auth_login_success: 'Welcome! Logged in successfully.',
    auth_login_error: 'Login failed.',
    auth_enter_real_name: 'Please enter your real name.',
    auth_enter_real_email: 'Please enter a valid, active email address.',
    auth_enter_real_phone: 'Please enter a real phone number.',
    auth_enter_strong_password: 'Please enter a strong password.',
    auth_passwords_mismatch: 'Passwords do not match. Please re-enter.',
    auth_verification_sent: 'A verification link has been sent to your email!',
    auth_account_created: 'Account created successfully!',
    auth_register_failed: 'Registration failed.',
    auth_email_verified_congrats: 'Congratulations! Your email has been verified.',
    auth_email_not_yet_verified: 'Email has not been verified yet. Check your inbox or spam folder.',
    auth_check_verify_error: 'Error checking verification status.',
    auth_resend_verify_success: 'Verification link resent! Check inbox or spam folder.',
    auth_resend_verify_error: 'Failed to resend link.',
    auth_enter_account_email: 'Please enter your account email address.',
    auth_reset_link_sent: 'Password reset link sent! Check your inbox or spam folder.',
    auth_reset_link_error: 'Failed to send password reset link.',
    account_title: 'Listener Account & Profile',
    account_sub: 'Your subscription, pass and personal info',
    active_pass_status: 'Active',
    monthly_pass_title: 'Monthly Pass',
    pass_modal_title: 'Goppo Kahini ₹20 Pass',
    pass_modal_sub: 'Instant UPI Payment • No screenshots or typing UTR',
    close_btn: 'Close',
    payment_success_title: 'Congratulations! Your ₹20 Pass is activated!',
    status_active_30d: 'Status: Active • 30 Days Unlimited',
    plan_label: 'Plan:',
    paid_amount_label: 'Paid Amount:',
    auto_fetched_utr: 'Auto-fetched UTR:',
    validity_label: 'Validity:',
    validity_next_30d: 'For the next 30 days',
    pass_unlocked_desc: 'Now you can enjoy all Goppo Kahini stories, mega episodes, and special chapters without interruption.',
    start_listening: 'Start Listening',
    not_logged_in_warn: 'You are not logged in yet!',
    login_benefit_note: 'Logging in keeps your pass and history safe forever.',
    login_first_google_email: 'Login first with Google or Email',
    login_active_badge: 'Logged In',
    select_sub_plan: 'Select Subscription Plan',
    popular_pass_badge: 'Popular Pass',
    days_30: '30 Days',
    days_365: '365 Days',
    monthly_pass_card: 'Monthly Pass',
    annual_pass_card: '12-Month Pass',
    annual_saver_badge: 'Annual Saver',
    per_month: '/ month',
    per_year: '/ year',
    official_upi_id: 'Official UPI ID',
    copy: 'Copy',
    upi_apps_hint: 'Pay using any UPI app (GPay, PhonePe, Paytm)',
    auto_detected_utr_label: 'Auto-detected Transaction ID (UTR):',
    auto_connected: 'Automatically Connected',
    user_no_type_hint: 'No manual typing needed',
    real_contact_info_label: 'Your Real Contact Details (No fake info):',
    real_name_placeholder: 'Your real name (e.g. John Doe)',
    real_email_placeholder: 'Your real email (Gmail/Yahoo)',
    real_phone_placeholder: 'Real mobile number (7-15 digits)',
    payment_done_activate_btn: 'Payment Done — Activate ₹20 Pass',
    pass_activating: 'Activating Pass...',
    no_screenshot_needed_desc: 'No screenshots or complicated forms needed. Complete the payment and tap below to instantly activate your ₹20 Pass.',
    account_days_remaining: 'days remaining',
    account_today_last_day: 'Today is the last day',
    account_renew_pass: 'Renew Pass',
    account_change_password: 'Change Password',
    password_min_chars: 'New password must be at least 6 characters long.',
    password_mismatch: 'New password and confirm password do not match.',
    password_changed_success: 'Password changed successfully!',
    password_change_failed: 'Password change failed.',
    reminder_test_preview: 'Reminder Test Preview:',
    days_7: '7 days',
    days_3: '3 days',
    days_1: '1 day',
    expired_label: 'Expired',
    my_sub_and_pass: 'My Subscription & Pass',
    refund_submitted_alert: '✓ Refund request submitted! Admin will verify and process the refund to your account.',
    pending_verification: 'Pending Verification',
    pending_verification_desc: 'Your payment UTR is pending admin verification. Your pass will be activated as soon as received.',
    paid_label: 'Paid:',
    your_utr: 'Your UTR:',
    current_plan_heading: 'Current Plan',
    active_badge_status: 'Active',
    start_date_label: 'Start Date:',
    expiry_renewal_label: 'Expiry / Renewal:',
    refund_pending_notice: 'Refund Request Under Review',
    refund_pending_desc: 'Your refund request is under review. The status will update to "Refunded" once processed.',
    refund_completed_notice: 'Refund Completed',
    refund_completed_desc: 'Your payment has been refunded via Bank/UPI.',
    sub_cancelled_notice: 'Subscription Cancelled',
    sub_cancelled_desc: 'Your current subscription has been cancelled. Click below to get a new pass.',
    activate_new_pass_btn: 'Activate New Pass',
    want_refund_btn: 'Want a refund?',
    cancel_pass_btn: 'Cancel Pass',
    refund_form_title: 'Refund Request Form',
    original_payment_label: 'Original Payment:',
    refund_reason_label: 'Reason for refund *',
    refund_reason_placeholder: 'e.g. accidental double payment / service issue...',
    send_request_btn: 'Send Request',
    confirm_cancel_question: 'Are you sure you want to cancel the pass?',
    cancel_consequence_desc: 'Cancelling the pass will stop automatic renewal.',
    cancel_reason_label: 'Reason for cancellation (optional):',
    cancel_reason_placeholder: 'e.g. taking a break from stories for a while',
    keep_pass_btn: 'No, keep it',
    yes_cancel_btn: 'Yes, cancel it',

    // Legal / Policy UI
    policy_privacy: 'Privacy Policy',
    policy_terms: 'Terms & Conditions',
    policy_data_deletion: 'Account & Data Deletion',
    policy_grievance: 'Grievance / Nodal Officer',
    policy_refund: 'Refund & Cancellation Policy',
    policy_subscription_terms: 'Subscription & Pass Terms',
    policy_community: 'Community Guidelines',
    policy_copyright: 'Copyright Policy',
    policy_disclaimer: 'Disclaimer & Content Warning',
    policy_third_party: 'Third-Party Services',
    policy_permissions: 'App Permissions & Data Usage',
    policy_legal_info: 'Legal Information & Jurisdiction',
    policy_contact: 'Contact & Support',
    policy_badge_count: '4 Policies',

    // Language Onboarding & Filtering
    language_onboarding_title: 'Choose Your Preferred Language',
    language_onboarding_subtitle: 'Welcome to Goppo Kahini! Select your language so audio stories and navigation can be tailored to you.',
    language_onboarding_bengali_desc: 'Authentic Bengali thrillers, horror & folk audio classics',
    language_onboarding_hindi_desc: 'Thrilling Hindi mysteries, folklore & soothing sleep audios',
    language_onboarding_english_desc: 'Classic Victorian thrillers, deep relaxations & global tales',
    language_onboarding_confirm: 'Confirm & Start Listening',
    language_filter_all: 'All Stories',
    language_filter_bn: 'বাংলা গল্প',
    language_filter_hi: 'हिन्दी कहानियाँ',
    language_filter_en: 'English Stories',
    language_filter_title: 'Story Language',

    // Notification Permission Prompt
    notification_prompt_title: 'Enable Story Notifications',
    notification_prompt_subtitle: 'Get instant alerts whenever new horror thrillers, mega episodes, and special subscriber discounts are released.',
    notification_prompt_enable: '🔔 Enable Notifications',
    notification_prompt_later: 'Maybe Later',
    notification_enabled_toast: '✅ Notifications successfully enabled! You will be alerted when new stories arrive.',
    notification_blocked_toast: '⚠️ Notification permission is blocked in browser/device settings. Please allow in system settings.',
  },
};

interface LanguageContextProps {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'gk_app_language';

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (saved === 'bn' || saved === 'hi' || saved === 'en') {
        return saved;
      }
    }
    return 'bn';
  });

  const setLanguage = (lang: AppLanguage) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
      document.documentElement.lang = lang;
    }
  };

  useEffect(() => {
    if (typeof window !== 'undefined') {
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to Bengali if missing in current language
    const bnDict = TRANSLATIONS.bn;
    if (bnDict && bnDict[key]) {
      return bnDict[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const defaultLanguageContext: LanguageContextProps = {
  language: 'bn',
  setLanguage: () => {},
  t: (key: string, fallback?: string): string => {
    const bnDict = TRANSLATIONS.bn;
    if (bnDict && bnDict[key]) {
      return bnDict[key];
    }
    return fallback || key;
  },
};

export const useLanguage = (): LanguageContextProps => {
  const context = useContext(LanguageContext);
  return context || defaultLanguageContext;
};
